JCC = javac
VPATH = src
# combining all to make the final executable
all: Main.class

# build the class files	
Main.class:
	$(JCC) src/*/*.java
	
#used to clean all class files
clean: 
	$(RM) src/*/*.class
